# Generated by Django 5.1.6 on 2025-02-17 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentitem',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
