# Generated by Django 5.1.6 on 2025-02-17 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0002_contentitem_is_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentitem',
            name='is_public',
        ),
        migrations.AddField(
            model_name='contentitem',
            name='visibility',
            field=models.CharField(choices=[('PUBLIC', 'PUBLIC'), ('LOGIN', 'LOGIN'), ('PAID', 'PAID')], default='PAID', max_length=6),
        ),
    ]
