# Generated by Django 5.1.6 on 2025-02-17 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0004_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='blurb',
            field=models.TextField(default='BEGINNER'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('BEGINNER', 'BEGINNER'), ('INTERMEDIATE', 'INTERMEDIATE')], default='BEGINNER', max_length=12),
            preserve_default=False,
        ),
    ]
