# Generated by Django 5.1.6 on 2025-02-17 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0005_course_blurb_course_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(null=True, verbose_name='Position')),
                ('content_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content_management.contentitem')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content_management.course')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
