# Generated by Django 5.1.6 on 2025-02-17 17:54

import django.db.models.deletion
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0006_coursecontent'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='coursecontent',
            name='content_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_order', to='content_management.contentitem'),
        ),
        migrations.AlterField(
            model_name='coursecontent',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='content_management.course'),
        ),
    ]
