# Generated by Django 5.1.6 on 2025-03-27 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0008_courseaccess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecontent',
            name='position',
            field=models.PositiveSmallIntegerField(default=1, null=True, verbose_name='Position'),
        ),
    ]
